### ISSUE TITLE
Build error on Windows 8.1 x64

### ISSUE THREAD

**Issue by jajakobyly** [jeaye/ncurses-rs#78]
I tried to build ncurses-rs from cargo.

Build log: https://gist.github.com/jajakobyly/fa09e29fc46f49cf4474 (quite a long one)
OS: Windows 8.1 x64
rustc version:
```
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
binary: rustc
commit-hash: a59de37e99060162a2674e3ff45409ac73595c0e
commit-date: 2015-05-13
build-date: 2015-05-14
host: x86_64-pc-windows-gnu
release: 1.0.0
```

**Comment by ithamsteri** [comment]
I have this problem too.

**Comment by jeaye** [comment]
I don't run any Windows machines, so I'm unable to look into this one. If you find anything out, we can certainly bring in a PR, as long as it's still compatible with the more posixy systems.

**Comment by achankf** [comment]
I have this problem with Windows 10 x64 too. By inspection of the codes, it seems like the problem is due to chtype being type u64 in ncurse.rs and c_ulong in ll.rs. According to the lastest commit of the libc crate, the Windows version of c_ulong is u32[1], not u64. The type mismatch problem is fixed in PR #110, in the sense that rustc can now compile the library. However, I am still struggling about linking libncursesw (maybe it's msys-ncursesw6?), so the changes are untested.

[1] see line 5 of https://github.com/rust-lang/libc/blob/66c337532663ae3673cdffd0949dab6c865dd694/src/windows.rs

**Comment by nabijaczleweli** [comment]
This still occurs on Windows x86_64 due to a shitload of `expected u32, found u64` errors, is there any way of resolving this non-intrusively?

**Comment by jeaye** [comment]
On Fri, Oct 07, 2016 at 03:54:57PM -0700, Jędrzej wrote:
> This still occurs on Windows x86_64 due to a shitload of `expected u32, found u64` errors, is there any way of resolving this non-intrusively?

I imagine you'd need to add a configuration check for Win64 and define an unsigned integer type to use that will be different for each system. From there, all of the occurrences of u32 would need to be replaced with it. That's pretty intrusive though.

**Comment by nabijaczleweli** [comment]
Non-intrusive from an end-user POV, I meant :P
Lemme try to have at this.

**Comment by nabijaczleweli** [comment]
This seems to make it compile for me:
```diff
diff --git a/src/ll.rs b/src/ll.rs
index 1b34a3d..c469e71 100644
--- a/src/ll.rs
+++ b/src/ll.rs
@@ -16,9 +16,6 @@ use libc::{ c_char, c_int, c_short, c_uint, c_ulong, c_void, FILE };
 pub type c_bool = ::libc::c_uchar;

 /* Intrinsic types. */
-#[cfg(target_arch = "x86_64")]
-pub type chtype = c_ulong;
-#[cfg(not(target_arch = "x86_64"))]
 pub type chtype = c_uint;
 pub type winttype = c_uint;

diff --git a/src/ncurses.rs b/src/ncurses.rs
index 9986f59..0bb5873 100644
--- a/src/ncurses.rs
+++ b/src/ncurses.rs
@@ -24,9 +24,6 @@ pub use self::panel::wrapper::*;
 pub use self::menu::wrapper::*;
 pub use self::menu::constants::*;

-#[cfg(target_arch = "x86_64")]
-pub type chtype = u64;
-#[cfg(not(target_arch = "x86_64"))]
 pub type chtype = u32;
 pub type winttype = u32;
```

Now linking it, that's a whole 'nother conundrum...

**Comment by snuk182** [comment]
Would not it be more correct to replace all the C primitive types from libc-based to std's [os::raw::*](https://doc.rust-lang.org/beta/std/os/raw/type.c_ulong.html), if you don't mind linking Rust std?
